// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: api/proto/firecracker/v1/firecracker.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CREATED     EventType = 1
	EventType_EVENT_TYPE_STARTED     EventType = 2
	EventType_EVENT_TYPE_STOPPED     EventType = 3
	EventType_EVENT_TYPE_DELETED     EventType = 4
	EventType_EVENT_TYPE_ERROR       EventType = 5
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_CREATED",
		2: "EVENT_TYPE_STARTED",
		3: "EVENT_TYPE_STOPPED",
		4: "EVENT_TYPE_DELETED",
		5: "EVENT_TYPE_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CREATED":     1,
		"EVENT_TYPE_STARTED":     2,
		"EVENT_TYPE_STOPPED":     3,
		"EVENT_TYPE_DELETED":     4,
		"EVENT_TYPE_ERROR":       5,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_firecracker_v1_firecracker_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_proto_firecracker_v1_firecracker_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{0}
}

// Common types
type VMState int32

const (
	VMState_VM_STATE_UNSPECIFIED VMState = 0
	VMState_VM_STATE_CREATING    VMState = 1
	VMState_VM_STATE_RUNNING     VMState = 2
	VMState_VM_STATE_STOPPING    VMState = 3
	VMState_VM_STATE_STOPPED     VMState = 4
	VMState_VM_STATE_DELETING    VMState = 5
	VMState_VM_STATE_ERROR       VMState = 6
)

// Enum value maps for VMState.
var (
	VMState_name = map[int32]string{
		0: "VM_STATE_UNSPECIFIED",
		1: "VM_STATE_CREATING",
		2: "VM_STATE_RUNNING",
		3: "VM_STATE_STOPPING",
		4: "VM_STATE_STOPPED",
		5: "VM_STATE_DELETING",
		6: "VM_STATE_ERROR",
	}
	VMState_value = map[string]int32{
		"VM_STATE_UNSPECIFIED": 0,
		"VM_STATE_CREATING":    1,
		"VM_STATE_RUNNING":     2,
		"VM_STATE_STOPPING":    3,
		"VM_STATE_STOPPED":     4,
		"VM_STATE_DELETING":    5,
		"VM_STATE_ERROR":       6,
	}
)

func (x VMState) Enum() *VMState {
	p := new(VMState)
	*p = x
	return p
}

func (x VMState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VMState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_firecracker_v1_firecracker_proto_enumTypes[1].Descriptor()
}

func (VMState) Type() protoreflect.EnumType {
	return &file_api_proto_firecracker_v1_firecracker_proto_enumTypes[1]
}

func (x VMState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VMState.Descriptor instead.
func (VMState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{1}
}

// CreateVM
type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	VcpuCount     int32                  `protobuf:"varint,2,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	KernelPath    string                 `protobuf:"bytes,5,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	RootfsPath    string                 `protobuf:"bytes,6,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVMRequest) GetVcpuCount() int32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *CreateVMRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateVMRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *CreateVMRequest) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *CreateVMRequest) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *CreateVMRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         VMState                `protobuf:"varint,2,opt,name=state,proto3,enum=firecracker.v1.VMState" json:"state,omitempty"`
	SocketPath    string                 `protobuf:"bytes,3,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVMResponse) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *CreateVMResponse) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *CreateVMResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateVMResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StartVM
type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{2}
}

func (x *StartVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         VMState                `protobuf:"varint,2,opt,name=state,proto3,enum=firecracker.v1.VMState" json:"state,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMResponse) Reset() {
	*x = StartVMResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMResponse) ProtoMessage() {}

func (x *StartVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMResponse.ProtoReflect.Descriptor instead.
func (*StartVMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{3}
}

func (x *StartVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StartVMResponse) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *StartVMResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// StopVM
type StopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{4}
}

func (x *StopVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVMRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type StopVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         VMState                `protobuf:"varint,2,opt,name=state,proto3,enum=firecracker.v1.VMState" json:"state,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMResponse) Reset() {
	*x = StopVMResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMResponse) ProtoMessage() {}

func (x *StopVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMResponse.ProtoReflect.Descriptor instead.
func (*StopVMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{5}
}

func (x *StopVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *StopVMResponse) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *StopVMResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// DeleteVM
type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DeleteVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMResponse) Reset() {
	*x = DeleteVMResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMResponse) ProtoMessage() {}

func (x *DeleteVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMResponse.ProtoReflect.Descriptor instead.
func (*DeleteVMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *DeleteVMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteVMResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GetVM
type GetVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMRequest) Reset() {
	*x = GetVMRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMRequest) ProtoMessage() {}

func (x *GetVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMRequest.ProtoReflect.Descriptor instead.
func (*GetVMRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{8}
}

func (x *GetVMRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type GetVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMInfo                `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMResponse) Reset() {
	*x = GetVMResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMResponse) ProtoMessage() {}

func (x *GetVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMResponse.ProtoReflect.Descriptor instead.
func (*GetVMResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{9}
}

func (x *GetVMResponse) GetVm() *VMInfo {
	if x != nil {
		return x.Vm
	}
	return nil
}

// ListVMs
type ListVMsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsRequest) Reset() {
	*x = ListVMsRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsRequest) ProtoMessage() {}

func (x *ListVMsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsRequest.ProtoReflect.Descriptor instead.
func (*ListVMsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{10}
}

func (x *ListVMsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListVMsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListVMsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vms           []*VMInfo              `protobuf:"bytes,1,rep,name=vms,proto3" json:"vms,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVMsResponse) Reset() {
	*x = ListVMsResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVMsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVMsResponse) ProtoMessage() {}

func (x *ListVMsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVMsResponse.ProtoReflect.Descriptor instead.
func (*ListVMsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{11}
}

func (x *ListVMsResponse) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *ListVMsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListVMsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// WatchVMEvents
type WatchVMEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // empty for all VMs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVMEventsRequest) Reset() {
	*x = WatchVMEventsRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVMEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVMEventsRequest) ProtoMessage() {}

func (x *WatchVMEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVMEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchVMEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{12}
}

func (x *WatchVMEventsRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type VMEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         VMState                `protobuf:"varint,2,opt,name=state,proto3,enum=firecracker.v1.VMState" json:"state,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type          EventType              `protobuf:"varint,5,opt,name=type,proto3,enum=firecracker.v1.EventType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMEvent) Reset() {
	*x = VMEvent{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMEvent) ProtoMessage() {}

func (x *VMEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMEvent.ProtoReflect.Descriptor instead.
func (*VMEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{13}
}

func (x *VMEvent) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMEvent) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *VMEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VMEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *VMEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

// GetHostInfo
type GetHostInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostInfoRequest) Reset() {
	*x = GetHostInfoRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoRequest) ProtoMessage() {}

func (x *GetHostInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoRequest.ProtoReflect.Descriptor instead.
func (*GetHostInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{14}
}

type GetHostInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Hostname          string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TotalCpus         int32                  `protobuf:"varint,2,opt,name=total_cpus,json=totalCpus,proto3" json:"total_cpus,omitempty"`
	TotalMemoryMb     int64                  `protobuf:"varint,3,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	AvailableMemoryMb int64                  `protobuf:"varint,4,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`
	RunningVms        int32                  `protobuf:"varint,5,opt,name=running_vms,json=runningVms,proto3" json:"running_vms,omitempty"`
	CpuUsage          float32                `protobuf:"fixed32,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	Version           string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetHostInfoResponse) Reset() {
	*x = GetHostInfoResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostInfoResponse) ProtoMessage() {}

func (x *GetHostInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostInfoResponse.ProtoReflect.Descriptor instead.
func (*GetHostInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{15}
}

func (x *GetHostInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetHostInfoResponse) GetTotalCpus() int32 {
	if x != nil {
		return x.TotalCpus
	}
	return 0
}

func (x *GetHostInfoResponse) GetTotalMemoryMb() int64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *GetHostInfoResponse) GetAvailableMemoryMb() int64 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *GetHostInfoResponse) GetRunningVms() int32 {
	if x != nil {
		return x.RunningVms
	}
	return 0
}

func (x *GetHostInfoResponse) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetHostInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// HealthCheck
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{16}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{17}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	State         VMState                `protobuf:"varint,2,opt,name=state,proto3,enum=firecracker.v1.VMState" json:"state,omitempty"`
	VcpuCount     int32                  `protobuf:"varint,3,opt,name=vcpu_count,json=vcpuCount,proto3" json:"vcpu_count,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	SocketPath    string                 `protobuf:"bytes,6,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_firecracker_v1_firecracker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP(), []int{18}
}

func (x *VMInfo) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMInfo) GetState() VMState {
	if x != nil {
		return x.State
	}
	return VMState_VM_STATE_UNSPECIFIED
}

func (x *VMInfo) GetVcpuCount() int32 {
	if x != nil {
		return x.VcpuCount
	}
	return 0
}

func (x *VMInfo) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *VMInfo) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *VMInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *VMInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_proto_firecracker_v1_firecracker_proto protoreflect.FileDescriptor

const file_api_proto_firecracker_v1_firecracker_proto_rawDesc = "" +
	"\n" +
	"*api/proto/firecracker/v1/firecracker.proto\x12\x0efirecracker.v1\"\xcb\x02\n" +
	"\x0fCreateVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x02 \x01(\x05R\tvcpuCount\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vkernel_path\x18\x05 \x01(\tR\n" +
	"kernelPath\x12\x1f\n" +
	"\vrootfs_path\x18\x06 \x01(\tR\n" +
	"rootfsPath\x12I\n" +
	"\bmetadata\x18\a \x03(\v2-.firecracker.v1.CreateVMRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x10CreateVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.firecracker.v1.VMStateR\x05state\x12\x1f\n" +
	"\vsocket_path\x18\x03 \x01(\tR\n" +
	"socketPath\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"%\n" +
	"\x0eStartVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"z\n" +
	"\x0fStartVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.firecracker.v1.VMStateR\x05state\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\":\n" +
	"\rStopVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"y\n" +
	"\x0eStopVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.firecracker.v1.VMStateR\x05state\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"&\n" +
	"\x0fDeleteVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"f\n" +
	"\x10DeleteVMResponse\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"#\n" +
	"\fGetVMRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"7\n" +
	"\rGetVMResponse\x12&\n" +
	"\x02vm\x18\x01 \x01(\v2\x16.firecracker.v1.VMInfoR\x02vm\"L\n" +
	"\x0eListVMsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x84\x01\n" +
	"\x0fListVMsResponse\x12(\n" +
	"\x03vms\x18\x01 \x03(\v2\x16.firecracker.v1.VMInfoR\x03vms\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"+\n" +
	"\x14WatchVMEventsRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"\xb4\x01\n" +
	"\aVMEvent\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.firecracker.v1.VMStateR\x05state\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.firecracker.v1.EventTypeR\x04type\"\x14\n" +
	"\x12GetHostInfoRequest\"\x80\x02\n" +
	"\x13GetHostInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"total_cpus\x18\x02 \x01(\x05R\ttotalCpus\x12&\n" +
	"\x0ftotal_memory_mb\x18\x03 \x01(\x03R\rtotalMemoryMb\x12.\n" +
	"\x13available_memory_mb\x18\x04 \x01(\x03R\x11availableMemoryMb\x12\x1f\n" +
	"\vrunning_vms\x18\x05 \x01(\x05R\n" +
	"runningVms\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x02R\bcpuUsage\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\"\x14\n" +
	"\x12HealthCheckRequest\"p\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\xe6\x02\n" +
	"\x06VMInfo\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.firecracker.v1.VMStateR\x05state\x12\x1d\n" +
	"\n" +
	"vcpu_count\x18\x03 \x01(\x05R\tvcpuCount\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x05R\bmemoryMb\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vsocket_path\x18\x06 \x01(\tR\n" +
	"socketPath\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12@\n" +
	"\bmetadata\x18\b \x03(\v2$.firecracker.v1.VMInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x9d\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CREATED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_STARTED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_STOPPED\x10\x03\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x04\x12\x14\n" +
	"\x10EVENT_TYPE_ERROR\x10\x05*\xa8\x01\n" +
	"\aVMState\x12\x18\n" +
	"\x14VM_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VM_STATE_CREATING\x10\x01\x12\x14\n" +
	"\x10VM_STATE_RUNNING\x10\x02\x12\x15\n" +
	"\x11VM_STATE_STOPPING\x10\x03\x12\x14\n" +
	"\x10VM_STATE_STOPPED\x10\x04\x12\x15\n" +
	"\x11VM_STATE_DELETING\x10\x05\x12\x12\n" +
	"\x0eVM_STATE_ERROR\x10\x062\xd9\x05\n" +
	"\x10FirecrackerAgent\x12M\n" +
	"\bCreateVM\x12\x1f.firecracker.v1.CreateVMRequest\x1a .firecracker.v1.CreateVMResponse\x12J\n" +
	"\aStartVM\x12\x1e.firecracker.v1.StartVMRequest\x1a\x1f.firecracker.v1.StartVMResponse\x12G\n" +
	"\x06StopVM\x12\x1d.firecracker.v1.StopVMRequest\x1a\x1e.firecracker.v1.StopVMResponse\x12M\n" +
	"\bDeleteVM\x12\x1f.firecracker.v1.DeleteVMRequest\x1a .firecracker.v1.DeleteVMResponse\x12D\n" +
	"\x05GetVM\x12\x1c.firecracker.v1.GetVMRequest\x1a\x1d.firecracker.v1.GetVMResponse\x12J\n" +
	"\aListVMs\x12\x1e.firecracker.v1.ListVMsRequest\x1a\x1f.firecracker.v1.ListVMsResponse\x12P\n" +
	"\rWatchVMEvents\x12$.firecracker.v1.WatchVMEventsRequest\x1a\x17.firecracker.v1.VMEvent0\x01\x12V\n" +
	"\vGetHostInfo\x12\".firecracker.v1.GetHostInfoRequest\x1a#.firecracker.v1.GetHostInfoResponse\x12V\n" +
	"\vHealthCheck\x12\".firecracker.v1.HealthCheckRequest\x1a#.firecracker.v1.HealthCheckResponseB>Z<github.com/apardo/mikrom-go/api/proto/firecracker/v1b\x06proto3"

var (
	file_api_proto_firecracker_v1_firecracker_proto_rawDescOnce sync.Once
	file_api_proto_firecracker_v1_firecracker_proto_rawDescData []byte
)

func file_api_proto_firecracker_v1_firecracker_proto_rawDescGZIP() []byte {
	file_api_proto_firecracker_v1_firecracker_proto_rawDescOnce.Do(func() {
		file_api_proto_firecracker_v1_firecracker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_firecracker_v1_firecracker_proto_rawDesc), len(file_api_proto_firecracker_v1_firecracker_proto_rawDesc)))
	})
	return file_api_proto_firecracker_v1_firecracker_proto_rawDescData
}

var file_api_proto_firecracker_v1_firecracker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_firecracker_v1_firecracker_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_firecracker_v1_firecracker_proto_goTypes = []any{
	(EventType)(0),               // 0: firecracker.v1.EventType
	(VMState)(0),                 // 1: firecracker.v1.VMState
	(*CreateVMRequest)(nil),      // 2: firecracker.v1.CreateVMRequest
	(*CreateVMResponse)(nil),     // 3: firecracker.v1.CreateVMResponse
	(*StartVMRequest)(nil),       // 4: firecracker.v1.StartVMRequest
	(*StartVMResponse)(nil),      // 5: firecracker.v1.StartVMResponse
	(*StopVMRequest)(nil),        // 6: firecracker.v1.StopVMRequest
	(*StopVMResponse)(nil),       // 7: firecracker.v1.StopVMResponse
	(*DeleteVMRequest)(nil),      // 8: firecracker.v1.DeleteVMRequest
	(*DeleteVMResponse)(nil),     // 9: firecracker.v1.DeleteVMResponse
	(*GetVMRequest)(nil),         // 10: firecracker.v1.GetVMRequest
	(*GetVMResponse)(nil),        // 11: firecracker.v1.GetVMResponse
	(*ListVMsRequest)(nil),       // 12: firecracker.v1.ListVMsRequest
	(*ListVMsResponse)(nil),      // 13: firecracker.v1.ListVMsResponse
	(*WatchVMEventsRequest)(nil), // 14: firecracker.v1.WatchVMEventsRequest
	(*VMEvent)(nil),              // 15: firecracker.v1.VMEvent
	(*GetHostInfoRequest)(nil),   // 16: firecracker.v1.GetHostInfoRequest
	(*GetHostInfoResponse)(nil),  // 17: firecracker.v1.GetHostInfoResponse
	(*HealthCheckRequest)(nil),   // 18: firecracker.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 19: firecracker.v1.HealthCheckResponse
	(*VMInfo)(nil),               // 20: firecracker.v1.VMInfo
	nil,                          // 21: firecracker.v1.CreateVMRequest.MetadataEntry
	nil,                          // 22: firecracker.v1.VMInfo.MetadataEntry
}
var file_api_proto_firecracker_v1_firecracker_proto_depIdxs = []int32{
	21, // 0: firecracker.v1.CreateVMRequest.metadata:type_name -> firecracker.v1.CreateVMRequest.MetadataEntry
	1,  // 1: firecracker.v1.CreateVMResponse.state:type_name -> firecracker.v1.VMState
	1,  // 2: firecracker.v1.StartVMResponse.state:type_name -> firecracker.v1.VMState
	1,  // 3: firecracker.v1.StopVMResponse.state:type_name -> firecracker.v1.VMState
	20, // 4: firecracker.v1.GetVMResponse.vm:type_name -> firecracker.v1.VMInfo
	20, // 5: firecracker.v1.ListVMsResponse.vms:type_name -> firecracker.v1.VMInfo
	1,  // 6: firecracker.v1.VMEvent.state:type_name -> firecracker.v1.VMState
	0,  // 7: firecracker.v1.VMEvent.type:type_name -> firecracker.v1.EventType
	1,  // 8: firecracker.v1.VMInfo.state:type_name -> firecracker.v1.VMState
	22, // 9: firecracker.v1.VMInfo.metadata:type_name -> firecracker.v1.VMInfo.MetadataEntry
	2,  // 10: firecracker.v1.FirecrackerAgent.CreateVM:input_type -> firecracker.v1.CreateVMRequest
	4,  // 11: firecracker.v1.FirecrackerAgent.StartVM:input_type -> firecracker.v1.StartVMRequest
	6,  // 12: firecracker.v1.FirecrackerAgent.StopVM:input_type -> firecracker.v1.StopVMRequest
	8,  // 13: firecracker.v1.FirecrackerAgent.DeleteVM:input_type -> firecracker.v1.DeleteVMRequest
	10, // 14: firecracker.v1.FirecrackerAgent.GetVM:input_type -> firecracker.v1.GetVMRequest
	12, // 15: firecracker.v1.FirecrackerAgent.ListVMs:input_type -> firecracker.v1.ListVMsRequest
	14, // 16: firecracker.v1.FirecrackerAgent.WatchVMEvents:input_type -> firecracker.v1.WatchVMEventsRequest
	16, // 17: firecracker.v1.FirecrackerAgent.GetHostInfo:input_type -> firecracker.v1.GetHostInfoRequest
	18, // 18: firecracker.v1.FirecrackerAgent.HealthCheck:input_type -> firecracker.v1.HealthCheckRequest
	3,  // 19: firecracker.v1.FirecrackerAgent.CreateVM:output_type -> firecracker.v1.CreateVMResponse
	5,  // 20: firecracker.v1.FirecrackerAgent.StartVM:output_type -> firecracker.v1.StartVMResponse
	7,  // 21: firecracker.v1.FirecrackerAgent.StopVM:output_type -> firecracker.v1.StopVMResponse
	9,  // 22: firecracker.v1.FirecrackerAgent.DeleteVM:output_type -> firecracker.v1.DeleteVMResponse
	11, // 23: firecracker.v1.FirecrackerAgent.GetVM:output_type -> firecracker.v1.GetVMResponse
	13, // 24: firecracker.v1.FirecrackerAgent.ListVMs:output_type -> firecracker.v1.ListVMsResponse
	15, // 25: firecracker.v1.FirecrackerAgent.WatchVMEvents:output_type -> firecracker.v1.VMEvent
	17, // 26: firecracker.v1.FirecrackerAgent.GetHostInfo:output_type -> firecracker.v1.GetHostInfoResponse
	19, // 27: firecracker.v1.FirecrackerAgent.HealthCheck:output_type -> firecracker.v1.HealthCheckResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_firecracker_v1_firecracker_proto_init() }
func file_api_proto_firecracker_v1_firecracker_proto_init() {
	if File_api_proto_firecracker_v1_firecracker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_firecracker_v1_firecracker_proto_rawDesc), len(file_api_proto_firecracker_v1_firecracker_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_firecracker_v1_firecracker_proto_goTypes,
		DependencyIndexes: file_api_proto_firecracker_v1_firecracker_proto_depIdxs,
		EnumInfos:         file_api_proto_firecracker_v1_firecracker_proto_enumTypes,
		MessageInfos:      file_api_proto_firecracker_v1_firecracker_proto_msgTypes,
	}.Build()
	File_api_proto_firecracker_v1_firecracker_proto = out.File
	file_api_proto_firecracker_v1_firecracker_proto_goTypes = nil
	file_api_proto_firecracker_v1_firecracker_proto_depIdxs = nil
}
