// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/firecracker/v1/firecracker.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FirecrackerAgent_CreateVM_FullMethodName      = "/firecracker.v1.FirecrackerAgent/CreateVM"
	FirecrackerAgent_StartVM_FullMethodName       = "/firecracker.v1.FirecrackerAgent/StartVM"
	FirecrackerAgent_StopVM_FullMethodName        = "/firecracker.v1.FirecrackerAgent/StopVM"
	FirecrackerAgent_DeleteVM_FullMethodName      = "/firecracker.v1.FirecrackerAgent/DeleteVM"
	FirecrackerAgent_GetVM_FullMethodName         = "/firecracker.v1.FirecrackerAgent/GetVM"
	FirecrackerAgent_ListVMs_FullMethodName       = "/firecracker.v1.FirecrackerAgent/ListVMs"
	FirecrackerAgent_WatchVMEvents_FullMethodName = "/firecracker.v1.FirecrackerAgent/WatchVMEvents"
	FirecrackerAgent_GetHostInfo_FullMethodName   = "/firecracker.v1.FirecrackerAgent/GetHostInfo"
	FirecrackerAgent_HealthCheck_FullMethodName   = "/firecracker.v1.FirecrackerAgent/HealthCheck"
)

// FirecrackerAgentClient is the client API for FirecrackerAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FirecrackerAgent service manages Firecracker microVMs
type FirecrackerAgentClient interface {
	// VM Lifecycle operations
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error)
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error)
	ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error)
	// Streaming
	WatchVMEvents(ctx context.Context, in *WatchVMEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VMEvent], error)
	// Host Management
	GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type firecrackerAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewFirecrackerAgentClient(cc grpc.ClientConnInterface) FirecrackerAgentClient {
	return &firecrackerAgentClient{cc}
}

func (c *firecrackerAgentClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVMResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVMResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) GetVM(ctx context.Context, in *GetVMRequest, opts ...grpc.CallOption) (*GetVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_GetVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) ListVMs(ctx context.Context, in *ListVMsRequest, opts ...grpc.CallOption) (*ListVMsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVMsResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_ListVMs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) WatchVMEvents(ctx context.Context, in *WatchVMEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VMEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FirecrackerAgent_ServiceDesc.Streams[0], FirecrackerAgent_WatchVMEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchVMEventsRequest, VMEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FirecrackerAgent_WatchVMEventsClient = grpc.ServerStreamingClient[VMEvent]

func (c *firecrackerAgentClient) GetHostInfo(ctx context.Context, in *GetHostInfoRequest, opts ...grpc.CallOption) (*GetHostInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostInfoResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_GetHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firecrackerAgentClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, FirecrackerAgent_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirecrackerAgentServer is the server API for FirecrackerAgent service.
// All implementations must embed UnimplementedFirecrackerAgentServer
// for forward compatibility.
//
// FirecrackerAgent service manages Firecracker microVMs
type FirecrackerAgentServer interface {
	// VM Lifecycle operations
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error)
	StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error)
	ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error)
	// Streaming
	WatchVMEvents(*WatchVMEventsRequest, grpc.ServerStreamingServer[VMEvent]) error
	// Host Management
	GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedFirecrackerAgentServer()
}

// UnimplementedFirecrackerAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirecrackerAgentServer struct{}

func (UnimplementedFirecrackerAgentServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedFirecrackerAgentServer) StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedFirecrackerAgentServer) StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedFirecrackerAgentServer) DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedFirecrackerAgentServer) GetVM(context.Context, *GetVMRequest) (*GetVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVM not implemented")
}
func (UnimplementedFirecrackerAgentServer) ListVMs(context.Context, *ListVMsRequest) (*ListVMsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVMs not implemented")
}
func (UnimplementedFirecrackerAgentServer) WatchVMEvents(*WatchVMEventsRequest, grpc.ServerStreamingServer[VMEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchVMEvents not implemented")
}
func (UnimplementedFirecrackerAgentServer) GetHostInfo(context.Context, *GetHostInfoRequest) (*GetHostInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedFirecrackerAgentServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFirecrackerAgentServer) mustEmbedUnimplementedFirecrackerAgentServer() {}
func (UnimplementedFirecrackerAgentServer) testEmbeddedByValue()                          {}

// UnsafeFirecrackerAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirecrackerAgentServer will
// result in compilation errors.
type UnsafeFirecrackerAgentServer interface {
	mustEmbedUnimplementedFirecrackerAgentServer()
}

func RegisterFirecrackerAgentServer(s grpc.ServiceRegistrar, srv FirecrackerAgentServer) {
	// If the following call panics, it indicates UnimplementedFirecrackerAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FirecrackerAgent_ServiceDesc, srv)
}

func _FirecrackerAgent_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_GetVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).GetVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_GetVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).GetVM(ctx, req.(*GetVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_ListVMs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVMsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).ListVMs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_ListVMs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).ListVMs(ctx, req.(*ListVMsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_WatchVMEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchVMEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FirecrackerAgentServer).WatchVMEvents(m, &grpc.GenericServerStream[WatchVMEventsRequest, VMEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FirecrackerAgent_WatchVMEventsServer = grpc.ServerStreamingServer[VMEvent]

func _FirecrackerAgent_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).GetHostInfo(ctx, req.(*GetHostInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirecrackerAgent_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirecrackerAgentServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirecrackerAgent_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirecrackerAgentServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirecrackerAgent_ServiceDesc is the grpc.ServiceDesc for FirecrackerAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirecrackerAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "firecracker.v1.FirecrackerAgent",
	HandlerType: (*FirecrackerAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _FirecrackerAgent_CreateVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _FirecrackerAgent_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _FirecrackerAgent_StopVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _FirecrackerAgent_DeleteVM_Handler,
		},
		{
			MethodName: "GetVM",
			Handler:    _FirecrackerAgent_GetVM_Handler,
		},
		{
			MethodName: "ListVMs",
			Handler:    _FirecrackerAgent_ListVMs_Handler,
		},
		{
			MethodName: "GetHostInfo",
			Handler:    _FirecrackerAgent_GetHostInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FirecrackerAgent_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchVMEvents",
			Handler:       _FirecrackerAgent_WatchVMEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/firecracker/v1/firecracker.proto",
}
